#include <LiquidCrystal.h>

#include <FastLED.h>

#define LED_PIN     7
#define NUM_LEDS    13
#define DELAY_TIME  220
#define BRIGHTNESS 100

CRGB leds[NUM_LEDS];

void setup() {

  pinMode(LED_PIN, OUTPUT);
  FastLED.addLeds<WS2812, LED_PIN, GRB>(leds, NUM_LEDS);

  for(int i=0; i<NUM_LEDS; i++){
    leds[i] = CRGB::Black;
  }
  
}

void loop() {
  
  leds[0] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[1] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[2] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[3] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[4] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[5] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[6] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[7] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[8] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[9] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[10] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[11] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);
  leds[12] = CRGB(BRIGHTNESS, BRIGHTNESS, BRIGHTNESS);

  FastLED.show();
}